/login:
  Controller: SecurityC
  Action: login

/register:
  Controller: SecurityC
  Action: register

/home:
  Controller: Main
  Action: home

/dashboard:
  Controller: Dashboard
  Action: index

/dashboard/users:
  Controller: Dashboard
  Action: getUsers

/dashboard/admins:
  Controller: Dashboard
  Action: getAdmins

/dashboard/add-user:
  Controller: Dashboard
  Action: addUserForm

/dashboard/addUser:
  Controller: Dashboard
  Action: addUser

/dashboard/updateUserForm:
  Controller: Dashboard
  Action: updateUserForm

/dashboard/updateUser:
  Controller: Dashboard
  Action: updateUser

/dashboard/deleteUser:
  Controller: Dashboard
  Action: deleteUser

/logout:
  Controller: SecurityC
  Action: logout

/resetpassword:
  Controller: SecurityC
  Action: showResetPasswordForm

/resetPasswordProcess:
  Controller: SecurityC
  Action: processResetPassword

/activate:
  Controller: SecurityC
  Action: activate
/create-page:
  Controller: "PageController"
  Action: "create"

/store-page:
  Controller: "PageController"
  Action: "store"

/view-page/{slug}:
  Controller: "PageController"
  Action: "view"

/list-page:
  Controller: "PageController"
  Action: "list"

/edit-page:
  Controller: "PageController"
  Action: "edit"
  Method: "GET"
  Role: ["admin", "editor"]

/delete-page:
  Controller: "PageController"
  Action: "delete"
